### ISSUE TITLE
Camera control -> Name of cam

### ISSUE THREAD

**Issue by S474N** [homebridge-plugins/homebridge-camera-ffmpeg#484]
In Accessories have all cameras name as "Camera control".

If user have defined "Name" in config.json, I think, that will better use this name, as name of cam.

**Comment by normen** [comment]
I don't have that issue, for me all cameras are named the way I named them in the "cameras" entry. The first "name" (outside of the cameras entry) is for the homebridge log only.

**Comment by S474N** [comment]
@normen this isn't issue, but enhancement. I know, that the name is for log purposes, but I think, that will be good in menu Accessories of Homebridge UI X.

**Comment by normen** [comment]
Okay, maybe you should have mentioned you are looking at the Accesories overview in Config-UI-X in insecure mode...

This is an issue in config-ui-x, not this plugin. It doesn't display the devices name, only its "displayName". I suggest that config-ui-x simply uses the name if theres no displayName configured. Otherwise another option is to rename the camera in HomeKit, which will give them a displayName that config-ui-x would pick up.

**Comment by S474N** [comment]
Yes, I mean this:
![Homebridge-Camera_control](https://user-images.githubusercontent.com/16512337/82046129-9cf60200-96b0-11ea-9cd0-1b2ceb997c19.png)

If isn't problem of this plugin, I'll open issue directly in Homebridge Config UI-X.
