### ISSUE TITLE
The same Vcodec Copy configuration doesn't work on ios 13.5, but it works fine on ios 12.

### ISSUE THREAD

**Issue by sergoo-lbt** [homebridge-plugins/homebridge-camera-ffmpeg#517]
There is a Hikvision i114 camera, and the following config: 
 "name": "hikcam",
 "manufacturer": "Hikvision",
                    "model": "HiWatch i114",
 "serial number": "192.168.0.15",
                    "firmwareRevision": "1.0",
 "video conference": {
                        "source": "-y-i rtsp://admin:@192.168.0.15:554/unicast",
                        "stillImageSource": "- i rtsp://admin:@192.168.0.15:554/unicast -vframes 1-r 1",
 "vcodec": "copy",
 "package size": 188,
 "audio": true,
 "debug": false
                    } 
On my Iphone x , ios 13.5, the video starts once out of 4-5 attempts. The snapshot is always updated well. And on my son's old iphone 6 on ios12, the video stream always works perfectly! I asked my friends, the same situation!

**Comment by iRayanKhan** [comment]
I am using iOS 13.5 since Beta 1, and the copy vcodec works fine for me.

**Comment by sergoo-lbt** [comment]
> I am using iOS 13.5 since Beta 1, and the copy vcodec works fine for me.

Can I see your config?

**Comment by l3nticular** [comment]
The copy vcodec will literally depend on the exact config of your camera, so while it might work for one camera, another might use a slightly-incompatible codec (maybe just due to camera bug), and older iOS might be more tolerant of it.  I'm not an ffmpeg expert, but could try to do it is run ffmpeg manually and save a minute or so of video to a file.  Then you can examine the metadata to figure out exactly what it's claiming is the format, and you could even try to play that video on both iPhones.

One complete guess is that since the iPhoneX is much newer they probably have more hardware decoders, and I wonder if they switched from a software decoder to a hardware decoder with the latest update and that hardware decoder can't deal with the data you're inputting.

**Comment by Elder-HVAC-Man** [comment]
I have just recently installed a couple of Wyze V2 cameras and the video stream only works on my older iPad.  My iPhone, wives iPad and another newer iPad does not show the live stream.  Does not throw any error messages.

**Comment by NorthernMan54** [comment]
Did you follow this?

https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/wiki/Tested-Configurations#wyzecam-v2-with-raspberry-pi-4-model-b

**Comment by Elder-HVAC-Man** [comment]
Yes, followed that exactly.  We did notice that the stream would come in rarely on one of the other iPads.

**Comment by hubert3** [comment]
Having similar issues on iOS 13.5.1, iPhone 11 Pro Max and macOS Catalina 10.15.5

The Tested Configurations wiki page needs to be expanded by what iOS version on what device each has been successfully viewed on.

I am not having any luck getting my original ARM-based Xiaofang camera (SD card image fanghacks_v0.2.0.zip) to stream smoothly via homebridge-camera-ffmpeg on my Raspberry Pi 4, even though the RTSP stream is 1080p and smooth viewed in VLC

Tried vcodec copy and a combination of a few other other parameters. Only getting a few still images and no moving video
